JCF: couple of tweaks and bugfixes

diff --git a/docs/user_sourcefile_example b/docs/user_sourcefile_example
--- a/docs/user_sourcefile_example
+++ b/docs/user_sourcefile_example
@@ -3,6 +3,7 @@ DAQINTERFACE_BASEDIR=$PWD
 
 export DAQINTERFACE_SETTINGS=$DAQINTERFACE_BASEDIR/docs/settings_example
 export DAQINTERFACE_KNOWN_BOARDREADERS_LIST=$DAQINTERFACE_BASEDIR/docs/known_boardreaders_list_example
+export DAQINTERFACE_FHICL_DIRECTORY=$DAQINTERFACE_BASEDIR/simple_test_config
 
 if [[ ! -e $DAQINTERFACE_SETTINGS ]]; then
    echo "Unable to find settings file \"$DAQINTERFACE_SETTINGS\"" >&2
@@ -14,6 +15,12 @@ if [[ ! -e $DAQINTERFACE_KNOWN_BOARDREADERS_LIST ]]; then
    echo "Unable to find boardreaders list file \"$DAQINTERFACE_KNOWN_BOARDREADERS_LIST\"" >&2
    export DAQINTERFACE_USER_SOURCEFILE_ERRNO=2
    return 
+fi
+
+if [[ ! -e $DAQINTERFACE_FHICL_DIRECTORY ]]; then
+   echo "Unable to find FHiCL configuration directory \"$DAQINTERFACE_FHICL_DIRECTORY\"" >&2
+   export DAQINTERFACE_USER_SOURCEFILE_ERRNO=3
+   return
 fi
 
 export DAQINTERFACE_USER_SOURCEFILE_ERRNO=0
